### ISSUE TITLE
how to install on Raspbian Buster?

### ISSUE THREAD

**Issue by tung256** [swesterfeld/gst123#27]
could someone please have a detailed guide on how to install?
this is all i see:
![image](https://user-images.githubusercontent.com/37672036/210124313-91709244-5100-4a9e-be5f-f58a580e9898.png)

and in Putty, i get error on the 1st try!
![image](https://user-images.githubusercontent.com/37672036/210124318-58c43602-be58-455c-bd47-bc4b215814b5.png)

i need to create a video looper. this [Adafruit guide](https://learn.adafruit.com/raspberry-pi-video-looper/installation) works great for rpi. but since i cant afford any rpi atm, i got a Libre LePotato. im told this GST123 program will work as a video looper (auto play a mp4 file from USB flash drive whenever the device boots up) https://github.com/swesterfeld/gst123 BUT how do i even install it?

**Comment by tung256** [comment]
nevermind. this command works!
sudo apt-get install gst123

**Comment by luzpaz** [comment]
Please close ticket.
